on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download rustup-init.exe (ARM64)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe" -OutFile "rustup-init.exe"

      - name: Install Rust (ARM64)
        shell: pwsh
        run: |
          Start-Process -FilePath ".\rustup-init.exe" -ArgumentList "-y" -Wait

      - name: Add Rust to PATH
        shell: pwsh
        run: |
          $cargoBin = "$env:USERPROFILE\.cargo\bin"
          echo "$cargoBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify Rust installation
        shell: pwsh
        run: |
          rustc --version
          cargo --version
