name: Test pkgconf on Windows ARM64

on:
  workflow_dispatch:

jobs:
  test-pkgconf:
    name: Install and check pkgconf
    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pkgconf via vcpkg
        shell: pwsh
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" arm64

          $env:VCPKG_ROOT = "C:\vcpkg"

          if (-not (Test-Path $env:VCPKG_ROOT)) {
            git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
          }

          Set-Location $env:VCPKG_ROOT

          if (-not (Test-Path ".\vcpkg.exe")) {
            ./bootstrap-vcpkg.bat -disableMetrics
          }

          ./vcpkg install pkgconf:arm64-windows

          $pkgconfPath = "$env:VCPKG_ROOT\installed\arm64-windows\tools\pkgconf"
          $env:PATH = "$pkgconfPath;$env:PATH"

          Copy-Item "$pkgconfPath\pkgconf.exe" "$pkgconfPath\pkg-config.exe"

          # Save the updated PATH for next steps
          echo "$pkgconfPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check pkg-config version
        run: pkg-config --version
