
name: compare-boost-install-timing

on:
  workflow_dispatch:

jobs:

    runs-on: windows-11-arm

    steps:
      - name: Measure install-boost action time
        shell: powershell
        run: |
          where python.exe

